version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: neuromail-db-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: saumya
      POSTGRES_DB: neuromail
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: neuromail-redis-dev
    ports:
      - "6379:6379"

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DATABASE_URL=postgresql://postgres:saumya@postgres:5432/neuromail
      - REDIS_URL=redis://redis:6379
      - GOOGLE_CLIENT_ID=your_client_id_here.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=your_client_secret_here
      - NEXTAUTH_SECRET=c0326410427c19685a11be0706240d99
      - NEXTAUTH_URL=http://localhost:3003
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
