"""phase4_intelligence_pipeline

Revision ID: 21909fe719fe
Revises: d91e8463333d
Create Date: 2026-05-30 14:57:39.666177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21909fe719fe'
down_revision: Union[str, Sequence[str], None] = 'd91e8463333d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_channels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('channel_type', sa.String(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_channels_id'), 'notification_channels', ['id'], unique=False)
    op.create_table('review_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_items_id'), 'review_items', ['id'], unique=False)
    op.create_table('rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('outcome', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.create_table('ai_enrichment_caches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('raw_email_id', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('intent', sa.String(), nullable=True),
    sa.Column('urgency', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raw_email_id'], ['raw_emails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_enrichment_caches_id'), 'ai_enrichment_caches', ['id'], unique=False)
    op.create_table('alert_histories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('performed_by', sa.String(), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_histories_id'), 'alert_histories', ['id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['notification_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_id'), 'notification_logs', ['id'], unique=False)
    op.add_column('alerts', sa.Column('rule_id', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('severity', sa.String(), nullable=False))
    op.add_column('alerts', sa.Column('deduplication_key', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('snoozed_until', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('snooze_reason', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
    op.add_column('alerts', sa.Column('assigned_to', sa.String(), nullable=True))
    op.add_column('alerts', sa.Column('occurrence_count', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_alerts_deduplication_key'), 'alerts', ['deduplication_key'], unique=False)
    op.create_foreign_key(None, 'alerts', 'rules', ['rule_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_index(op.f('ix_alerts_deduplication_key'), table_name='alerts')
    op.drop_column('alerts', 'occurrence_count')
    op.drop_column('alerts', 'assigned_to')
    op.drop_column('alerts', 'acknowledged_at')
    op.drop_column('alerts', 'resolved_at')
    op.drop_column('alerts', 'snooze_reason')
    op.drop_column('alerts', 'snoozed_until')
    op.drop_column('alerts', 'deduplication_key')
    op.drop_column('alerts', 'severity')
    op.drop_column('alerts', 'rule_id')
    op.drop_index(op.f('ix_notification_logs_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_alert_histories_id'), table_name='alert_histories')
    op.drop_table('alert_histories')
    op.drop_index(op.f('ix_ai_enrichment_caches_id'), table_name='ai_enrichment_caches')
    op.drop_table('ai_enrichment_caches')
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_review_items_id'), table_name='review_items')
    op.drop_table('review_items')
    op.drop_index(op.f('ix_notification_channels_id'), table_name='notification_channels')
    op.drop_table('notification_channels')
    # ### end Alembic commands ###
