"""Add enterprise freight models

Revision ID: 4a37bc1722d9
Revises: 303e6972196b
Create Date: 2026-06-03 00:48:07.131013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a37bc1722d9'
down_revision: Union[str, Sequence[str], None] = '303e6972196b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freight_approvals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('approval_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_approvals_id'), 'freight_approvals', ['id'], unique=False)
    op.create_table('freight_audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_audit_logs_id'), 'freight_audit_logs', ['id'], unique=False)
    op.create_table('freight_job_failures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('job_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=False),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_job_failures_id'), 'freight_job_failures', ['id'], unique=False)
    op.create_table('freight_provider_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('provider_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('connection_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_provider_connections_id'), 'freight_provider_connections', ['id'], unique=False)
    op.create_table('freight_system_health_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('snapshot_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_system_health_snapshots_id'), 'freight_system_health_snapshots', ['id'], unique=False)
    op.create_table('freight_tenant_onboarding',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('step_mailbox_connected', sa.Boolean(), nullable=False),
    sa.Column('step_patterns_configured', sa.Boolean(), nullable=False),
    sa.Column('step_carriers_configured', sa.Boolean(), nullable=False),
    sa.Column('step_notifications_configured', sa.Boolean(), nullable=False),
    sa.Column('step_ingestion_validated', sa.Boolean(), nullable=False),
    sa.Column('step_sync_validated', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('freight_tenant_onboarding')
    op.drop_index(op.f('ix_freight_system_health_snapshots_id'), table_name='freight_system_health_snapshots')
    op.drop_table('freight_system_health_snapshots')
    op.drop_index(op.f('ix_freight_provider_connections_id'), table_name='freight_provider_connections')
    op.drop_table('freight_provider_connections')
    op.drop_index(op.f('ix_freight_job_failures_id'), table_name='freight_job_failures')
    op.drop_table('freight_job_failures')
    op.drop_index(op.f('ix_freight_audit_logs_id'), table_name='freight_audit_logs')
    op.drop_table('freight_audit_logs')
    op.drop_index(op.f('ix_freight_approvals_id'), table_name='freight_approvals')
    op.drop_table('freight_approvals')
    # ### end Alembic commands ###
