"""phase1_freight_core

Revision ID: 730939caf8bb
Revises: b065ef1b5ef8
Create Date: 2026-06-02 18:07:39.296897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730939caf8bb'
down_revision: Union[str, Sequence[str], None] = 'b065ef1b5ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freight_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('subject_patterns', sa.JSON(), nullable=False),
    sa.Column('from_addresses', sa.JSON(), nullable=False),
    sa.Column('last_ingestion_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_index(op.f('ix_freight_configs_id'), 'freight_configs', ['id'], unique=False)
    op.create_table('freight_shipments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('primary_reference', sa.String(), nullable=False),
    sa.Column('carrier', sa.String(), nullable=True),
    sa.Column('origin_port', sa.String(), nullable=True),
    sa.Column('destination_port', sa.String(), nullable=True),
    sa.Column('eta', sa.DateTime(), nullable=True),
    sa.Column('last_known_status', sa.String(), nullable=True),
    sa.Column('last_status_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status_source', sa.String(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_shipments_id'), 'freight_shipments', ['id'], unique=False)
    op.create_index(op.f('ix_freight_shipments_primary_reference'), 'freight_shipments', ['primary_reference'], unique=False)
    op.create_table('freight_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('shipment_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['freight_shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_events_id'), 'freight_events', ['id'], unique=False)
    op.create_table('freight_raw_emails',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('mailbox_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_message_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=True),
    sa.Column('from_address', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('raw_headers', sa.JSON(), nullable=True),
    sa.Column('raw_body', sa.Text(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.Column('parsing_status', sa.String(), nullable=False),
    sa.Column('parsing_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailboxes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', 'provider_message_id', name='uq_freight_raw_email_message')
    )
    op.create_index(op.f('ix_freight_raw_emails_id'), 'freight_raw_emails', ['id'], unique=False)
    op.create_index(op.f('ix_freight_raw_emails_provider_message_id'), 'freight_raw_emails', ['provider_message_id'], unique=False)
    op.create_table('freight_shipment_identifiers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('shipment_id', sa.String(), nullable=False),
    sa.Column('identifier_type', sa.String(), nullable=False),
    sa.Column('identifier_value', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['freight_shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'identifier_type', 'identifier_value', name='uq_freight_shipment_identifier')
    )
    op.create_index(op.f('ix_freight_shipment_identifiers_id'), 'freight_shipment_identifiers', ['id'], unique=False)
    op.create_table('freight_email_extractions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('raw_email_id', sa.String(), nullable=False),
    sa.Column('shipment_id', sa.String(), nullable=True),
    sa.Column('extraction_status', sa.String(), nullable=False),
    sa.Column('extracted_fields', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raw_email_id'], ['freight_raw_emails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shipment_id'], ['freight_shipments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_email_extractions_id'), 'freight_email_extractions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_freight_email_extractions_id'), table_name='freight_email_extractions')
    op.drop_table('freight_email_extractions')
    op.drop_index(op.f('ix_freight_shipment_identifiers_id'), table_name='freight_shipment_identifiers')
    op.drop_table('freight_shipment_identifiers')
    op.drop_index(op.f('ix_freight_raw_emails_provider_message_id'), table_name='freight_raw_emails')
    op.drop_index(op.f('ix_freight_raw_emails_id'), table_name='freight_raw_emails')
    op.drop_table('freight_raw_emails')
    op.drop_index(op.f('ix_freight_events_id'), table_name='freight_events')
    op.drop_table('freight_events')
    op.drop_index(op.f('ix_freight_shipments_primary_reference'), table_name='freight_shipments')
    op.drop_index(op.f('ix_freight_shipments_id'), table_name='freight_shipments')
    op.drop_table('freight_shipments')
    op.drop_index(op.f('ix_freight_configs_id'), table_name='freight_configs')
    op.drop_table('freight_configs')
    # ### end Alembic commands ###
