"""phase2_freight_tracking

Revision ID: b3f50455722d
Revises: 730939caf8bb
Create Date: 2026-06-02 20:34:25.056153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f50455722d'
down_revision: Union[str, Sequence[str], None] = '730939caf8bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('freight_sync_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('run_type', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_shipments', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_sync_runs_id'), 'freight_sync_runs', ['id'], unique=False)
    op.create_table('freight_tenant_configs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('no_update_threshold_hours', sa.Integer(), nullable=False),
    sa.Column('storage_risk_days', sa.Integer(), nullable=False),
    sa.Column('freight_subject_patterns', sa.JSON(), nullable=True),
    sa.Column('freight_from_addresses', sa.JSON(), nullable=True),
    sa.Column('active_carriers', sa.JSON(), nullable=True),
    sa.Column('notification_email_addresses', sa.JSON(), nullable=True),
    sa.Column('slack_webhook_url', sa.String(), nullable=True),
    sa.Column('external_webhook_url', sa.String(), nullable=True),
    sa.Column('alert_severity_threshold', sa.String(), nullable=False),
    sa.Column('mute_start_hour', sa.Integer(), nullable=True),
    sa.Column('mute_end_hour', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_index(op.f('ix_freight_tenant_configs_id'), 'freight_tenant_configs', ['id'], unique=False)
    op.create_table('freight_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('shipment_id', sa.String(), nullable=False),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('dedup_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('snoozed_until', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['freight_shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_alerts_id'), 'freight_alerts', ['id'], unique=False)
    op.create_table('freight_carrier_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('shipment_id', sa.String(), nullable=False),
    sa.Column('carrier_adapter', sa.String(), nullable=False),
    sa.Column('reference_used', sa.String(), nullable=False),
    sa.Column('carrier_status', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('eta', sa.DateTime(), nullable=True),
    sa.Column('vessel_name', sa.String(), nullable=True),
    sa.Column('last_event', sa.String(), nullable=True),
    sa.Column('last_event_at', sa.DateTime(), nullable=True),
    sa.Column('is_arrived', sa.Boolean(), nullable=False),
    sa.Column('is_delayed', sa.Boolean(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['freight_shipments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_carrier_snapshots_id'), 'freight_carrier_snapshots', ['id'], unique=False)
    op.create_table('freight_alert_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['freight_alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freight_alert_events_id'), 'freight_alert_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_freight_alert_events_id'), table_name='freight_alert_events')
    op.drop_table('freight_alert_events')
    op.drop_index(op.f('ix_freight_carrier_snapshots_id'), table_name='freight_carrier_snapshots')
    op.drop_table('freight_carrier_snapshots')
    op.drop_index(op.f('ix_freight_alerts_id'), table_name='freight_alerts')
    op.drop_table('freight_alerts')
    op.drop_index(op.f('ix_freight_tenant_configs_id'), table_name='freight_tenant_configs')
    op.drop_table('freight_tenant_configs')
    op.drop_index(op.f('ix_freight_sync_runs_id'), table_name='freight_sync_runs')
    op.drop_table('freight_sync_runs')
    # ### end Alembic commands ###
