"""add demo_featured to tenants

Revision ID: c0600de7d948
Revises: 4a37bc1722d9
Create Date: 2026-06-04 00:19:55.731107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0600de7d948'
down_revision: Union[str, Sequence[str], None] = '4a37bc1722d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'mailbox_connections' not in tables:
        op.create_table('mailbox_connections',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('tenant_id', sa.String(), nullable=False),
        sa.Column('provider', sa.String(), nullable=False),
        sa.Column('email_address', sa.String(), nullable=False),
        sa.Column('external_account_id', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('scopes', sa.JSON(), nullable=True),
        sa.Column('access_token_encrypted', sa.Text(), nullable=True),
        sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
        sa.Column('token_expires_at', sa.DateTime(), nullable=True),
        sa.Column('last_successful_sync_at', sa.DateTime(), nullable=True),
        sa.Column('last_failed_sync_at', sa.DateTime(), nullable=True),
        sa.Column('failure_reason', sa.String(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_mailbox_connections_id'), 'mailbox_connections', ['id'], unique=False)

    if 'freight_copilot_queries' not in tables:
        op.create_table('freight_copilot_queries',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('tenant_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('query_text', sa.Text(), nullable=False),
        sa.Column('response_mode', sa.String(), nullable=False),
        sa.Column('cited_object_refs', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_freight_copilot_queries_id'), 'freight_copilot_queries', ['id'], unique=False)

    # Columns
    if 'freight_tenant_onboarding' in tables:
        columns = [c['name'] for c in inspector.get_columns('freight_tenant_onboarding')]
        if 'step_outlook_connected' not in columns:
            op.add_column('freight_tenant_onboarding', sa.Column('step_outlook_connected', sa.Boolean(), server_default='0', nullable=False))

    if 'tenants' in tables:
        columns = [c['name'] for c in inspector.get_columns('tenants')]
        if 'demo_featured' not in columns:
            op.add_column('tenants', sa.Column('demo_featured', sa.Boolean(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'demo_featured')
    op.drop_column('freight_tenant_onboarding', 'step_outlook_connected')
    op.drop_index(op.f('ix_freight_copilot_queries_id'), table_name='freight_copilot_queries')
    op.drop_table('freight_copilot_queries')
    op.drop_index(op.f('ix_mailbox_connections_id'), table_name='mailbox_connections')
    op.drop_table('mailbox_connections')
    # ### end Alembic commands ###
