"""phase3_auth_and_attachments

Revision ID: d91e8463333d
Revises: a063f0af8db9
Create Date: 2026-05-30 14:17:07.772194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd91e8463333d'
down_revision: Union[str, Sequence[str], None] = 'a063f0af8db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('raw_email_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['raw_email_id'], ['raw_emails.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_id'), 'attachments', ['id'], unique=False)
    op.add_column('mailboxes', sa.Column('encrypted_access_token', sa.Text(), nullable=True))
    op.add_column('mailboxes', sa.Column('encrypted_refresh_token', sa.Text(), nullable=True))
    op.add_column('mailboxes', sa.Column('access_token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('mailboxes', sa.Column('last_history_id', sa.String(), nullable=True))
    op.add_column('mailboxes', sa.Column('webhook_subscription_id', sa.String(), nullable=True))
    op.add_column('mailboxes', sa.Column('webhook_subscription_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailboxes', 'webhook_subscription_expires_at')
    op.drop_column('mailboxes', 'webhook_subscription_id')
    op.drop_column('mailboxes', 'last_history_id')
    op.drop_column('mailboxes', 'access_token_expires_at')
    op.drop_column('mailboxes', 'encrypted_refresh_token')
    op.drop_column('mailboxes', 'encrypted_access_token')
    op.drop_index(op.f('ix_attachments_id'), table_name='attachments')
    op.drop_table('attachments')
    # ### end Alembic commands ###
